# Generated by Django 4.0.6 on 2022-07-16 14:58

import apps.core.models
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', apps.core.models.EmailField(max_length=254)),
                ('zion_member', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('leader', models.BooleanField(default=True)),
                ('zion_distance', models.IntegerField(choices=[(10, 'Ate 10 KM'), (20, 'Ate 20 KM'), (30, 'Ate 30 KM'), (40, 'Ate 40 KM'), (50, 'Ate 50 KM'), (100, 'Mais 100 KM')])),
                ('birth_date', models.DateField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
