# Generated by Django 4.0.6 on 2022-07-16 23:45

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=apps.core.models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='zion_member',
            field=models.BooleanField(default=False),
        ),
    ]
