# Generated by Django 4.0.6 on 2022-07-12 01:43

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_scheduler_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysWeekPresbytery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoursDaysPresbytery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('hours', models.TimeField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='daysweek',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hoursdays',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scheduler',
            options={},
        ),
        migrations.CreateModel(
            name='SchedulerPresbytery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', apps.core.models.EmailField(max_length=254, unique=True)),
                ('cellphone', models.CharField(max_length=12, unique=True)),
                ('areas', models.CharField(default='', max_length=20)),
                ('days_week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.daysweek')),
                ('hours_days', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.hoursdays')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
