# Generated by Django 4.0.6 on 2022-07-12 12:34

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_schedulerpresbytery_days_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='cellphone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='email',
            field=apps.core.models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schedulerpresbytery',
            name='cellphone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='schedulerpresbytery',
            name='email',
            field=apps.core.models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='schedulerpresbytery',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
