repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-docstring-first

#   - repo: https://github.com/ambv/black
#     rev: 22.3.0
#     hooks:
#       - id: black
#         language_version: python3.10

#   - repo: https://github.com/pycqa/flake8
#     rev: 4.0.1
#     hooks:
#       - id: flake8
#         additional_dependencies:
#           - flake8-bugbear
#           - flake8-comprehensions
#           - flake8-simplify
#   - repo: https://github.com/commitizen-tools/commitizen
#     rev: master
#     hooks:
#       - id: commitizen