version: "3"

services:
  prayer_room_schedule:
    container_name: prayer_room_schedule
    entrypoint: python manage.py runserver 0.0.0.0:8000
    tty: true
    stdin_open: true
    image: container_prayer-room-schedule
    build:
      context: .
    environment:
      - DATABASE_URI=${DATABASE_URI}
    volumes:
      - ./:/code/prayer_room_schedule/
    depends_on:
      service.postgres:
        condition: service_started
    ports:
      - "8000:8000"

  tasks-migrate:
    container_name: migrate
    image: container_prayer-room-schedule
    build:
      context: .
    tty: true
    stdin_open: true
    environment:
      - DATABASE_URI=${DATABASE_URI}
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      service.postgres:
        condition: service_started

  service.postgres:
    container_name: postgres_prayer_room_schedule
    image: postgres
    volumes:
      - postgre-data-test:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=tom
      - POSTGRES_PASSWORD=tom123
      - POSTGRES_DB=prayer_room_schedule

volumes:
  postgre-data-test: